"""Enumeration order must not depend on the process that computed it.

`docs/audit_log.md` finding 18. `TemplateSlot.accepted_categories` is a
``frozenset``; Python randomises string hashes per process; ``CandidatePool.
for_slot`` iterated it directly. So candidate order, combination order, and
every transcript `demo.py` produced varied between runs of identical code on the
same machine.

Why that is worth a test file rather than a comment: the whole point of
`demo.py` is that the evidence in `docs/audit_log.md` can be regenerated by
anyone. Substance reproduced -- verdicts, bounds and violations were stable
across 12 seeds -- but two people running the same command got textually
different transcripts, and a diff between them showed changes that were not
changes. Reproducibility rules keep being satisfied literally while missing
their purpose; this file is the mechanical check that replaces the promise.

Two tests, deliberately different in kind:

* ``TestOrderDoesNotDependOnCategoryIteration`` drives the mechanism directly
  and is fast. It is the one that pins the contract.
* ``TestOrderIsStableAcrossProcesses`` actually runs subprocesses under
  different ``PYTHONHASHSEED`` values. Slower, and the only test here that
  reproduces the original defect the way a user would meet it.
"""

from __future__ import annotations

import dataclasses
import subprocess
import sys
from pathlib import Path

import pytest

from core.foods.templates import template_for
from core.planner.candidates import build_candidate_pool
from core.planner.combinations import enumerate_combinations
from core.planner.plan import load_library
from core.schemas import DietPattern, MealSlot, Region

REPO_ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture(scope="module")
def north_lunch_pool():
    library = load_library()
    return build_candidate_pool(
        library.components(),
        library.ingredients,
        template=template_for(Region.NORTH_INDIAN, MealSlot.LUNCH),
        diet_pattern=DietPattern.VEGETARIAN,
        dev_mode=True,
    )


def _permuted(template, reverse: bool):
    """``template`` with every slot's categories as an explicit tuple.

    Both directions substitute a *tuple*, and neither reads the frozenset. That
    matters: comparing a substituted order against the raw frozenset would make
    the test pass or fail on whatever order this process's hash seed happens to
    produce -- which is the very thing under test, and it is how the first draft
    of these tests passed against the defect they were written to catch.
    """

    return dataclasses.replace(
        template,
        slots=tuple(
            dataclasses.replace(
                s,
                accepted_categories=tuple(
                    sorted(s.accepted_categories, reverse=reverse)
                ),
            )
            for s in template.slots
        ),
    )


class TestOrderDoesNotDependOnCategoryIteration:
    """Permute the category order; the candidate order must not move.

    ``accepted_categories`` is declared a ``frozenset``, and two frozensets with
    the same members iterate identically -- so the defect cannot be reproduced
    by building the set differently. It is reproduced by substituting a *tuple*,
    which is what a frozenset's arbitrary iteration order amounts to from
    ``for_slot``'s point of view. Nothing enforces the annotation at runtime,
    which is exactly why the annotation was not protection.
    """

    @staticmethod
    def _multi_category_slot(pool):
        """A slot with candidates in more than one category, or skip.

        The precondition is *populated* categories, not declared ones. A slot
        declaring three categories with candidates in only one returns the same
        answer under every permutation, so it cannot detect anything --
        `north_lunch.grain_base` accepts rice and roti and the library has only
        roti, and picking it is how the first draft of this test passed against
        the defect.
        """

        for slot in pool.template.slots:
            populated = [c for c in slot.accepted_categories if c in pool.by_category]
            if len(populated) > 1:
                return slot
        pytest.skip("no slot has candidates in more than one category")

    def test_candidates_are_identical_under_every_category_permutation(
        self, north_lunch_pool
    ):
        slot = self._multi_category_slot(north_lunch_pool)
        categories = sorted(slot.accepted_categories)
        results = [
            tuple(
                c.id
                for c in north_lunch_pool.for_slot(
                    dataclasses.replace(slot, accepted_categories=order)
                )
            )
            for order in (tuple(categories), tuple(reversed(categories)))
        ]
        assert results[0] == results[1]
        assert len(results[0]) > 1, "a one-candidate slot proves nothing here"

    def test_candidates_come_back_sorted_by_id(self, north_lunch_pool):
        # The contract, stated -- but NOT a reliable detector of the original
        # defect, and it must not be mistaken for one: unsorted frozenset order
        # coincides with sorted order often enough that this passes under many
        # hash seeds. `TestOrderIsStableAcrossProcesses` is the detector.
        slot = self._multi_category_slot(north_lunch_pool)
        ids = [c.id for c in north_lunch_pool.for_slot(slot)]
        assert ids == sorted(ids)

    def test_enumeration_is_identical_under_every_category_permutation(
        self, north_lunch_pool
    ):
        # for_slot feeds itertools.product, so an unstable slot order becomes an
        # unstable combination order. Asserted at the level a transcript shows.
        both = [
            [
                [c.id for c in combo.components]
                for combo in enumerate_combinations(
                    dataclasses.replace(
                        north_lunch_pool,
                        template=_permuted(north_lunch_pool.template, reverse),
                    )
                )
            ]
            for reverse in (False, True)
        ]
        assert both[0], "fixture assumption changed: north_lunch enumerates nothing"
        assert both[0] == both[1]


class TestOrderIsStableAcrossProcesses:
    """The end-to-end check: real subprocesses, real hash seeds.

    This is the only test here that reproduces the defect the way it was found.
    It costs four interpreter starts, which is worth it once: the fast test
    above pins the mechanism, and this one pins that the mechanism was the whole
    of it.
    """

    SNIPPET = (
        "from core.foods.templates import template_for;"
        "from core.planner.candidates import build_candidate_pool;"
        "from core.planner.combinations import enumerate_combinations;"
        "from core.planner.plan import load_library;"
        "from core.schemas import DietPattern, MealSlot, Region;"
        "lib = load_library();"
        "pool = build_candidate_pool(lib.components(), lib.ingredients,"
        "  template=template_for(Region.NORTH_INDIAN, MealSlot.LUNCH),"
        "  diet_pattern=DietPattern.VEGETARIAN, dev_mode=True);"
        "print([[c.id for c in k.components] for k in enumerate_combinations(pool)])"
    )

    def _run(self, seed: str) -> str:
        result = subprocess.run(
            [sys.executable, "-c", self.SNIPPET],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            env={"PYTHONHASHSEED": seed, "PYTHONPATH": str(REPO_ROOT),
                 "PATH": "", "SYSTEMROOT": ""},
        )
        assert result.returncode == 0, result.stderr
        return result.stdout.strip()

    def test_four_hash_seeds_produce_one_enumeration(self):
        outputs = {seed: self._run(seed) for seed in ("0", "1", "2", "7")}
        distinct = set(outputs.values())
        assert len(distinct) == 1, (
            "enumeration order depends on PYTHONHASHSEED (finding 18):\n"
            + "\n".join(f"  seed {s}: {o}" for s, o in outputs.items())
        )
        assert distinct.pop().startswith("[["), "expected a non-empty enumeration"
