"""Smoke tests for the `demo.py` entry point.

Deliberately shallow. These assert that the script *runs* and *emits the
sections it promises* -- nothing about what any number is. Nutrition values are
pinned in `tests/test_recipes.py`, `tests/test_nutrition_targets.py` and
`tests/test_planner_plan.py`, where a change to one shows up as a failure that
names the quantity. Asserting a gram value here would duplicate that coverage
in a place where a failure says only "the demo changed".

What these DO protect is the property the script exists for: that the evidence
in `docs/audit_log.md` can be regenerated by a command anyone can run. A script
that crashes on a flag, or silently stops printing the unrelaxed target, breaks
that promise without breaking any nutrition test.
"""

from __future__ import annotations

import pytest

import demo


def _run(capsys, argv):
    assert demo.main(argv) == 0
    return capsys.readouterr().out


class TestItRuns:
    def test_default_invocation_needs_no_arguments(self, capsys):
        # `python demo.py` with nothing else must reproduce the full run, not
        # print usage: the reference transcript is the zero-argument one.
        out = _run(capsys, [])
        assert "1. LOAD THE REAL LIBRARY" in out
        assert "2. SLOT COVERAGE" in out
        assert "3. ENUMERATION" in out
        assert "4. plan_meal()" in out

    @pytest.mark.parametrize("command", ["library", "plan", "all"])
    def test_each_subcommand_runs(self, capsys, command):
        assert _run(capsys, [command]).strip()

    def test_library_stops_before_the_plan_sections(self, capsys):
        out = _run(capsys, ["library"])
        assert "1. LOAD THE REAL LIBRARY" in out
        assert "4. plan_meal()" not in out


class TestTheOutputCarriesItsOwnCaveats:
    def test_status_appears_at_both_ends(self, capsys):
        # docs/methodology.md: a dev_mode artifact must carry the label in the
        # artifact itself, because a pasted transcript outlives its context.
        # Both ends, so a truncated paste still shows it.
        out = _run(capsys, ["plan"])
        assert "STATUS: DEV_MODE" in out
        assert out.strip().splitlines()[-2].strip().startswith("END OF RUN")
        assert "DEV_MODE" in out.strip().splitlines()[-2]

    def test_both_targets_are_printed_and_distinguishable(self, capsys):
        # The Task 4b miscalibration: only `target_used` was printed, under a
        # bare "meal target" heading, so fully-relaxed bounds were read as the
        # bounds the plate was first asked to meet. Printing one without the
        # other is the bug this asserts against.
        out = _run(capsys, ["plan"])
        assert "TARGET AS ASKED" in out
        assert "unrelaxed" in out
        assert "TARGET AS SOLVED" in out

    def test_a_declining_run_still_prints_violations_and_a_disclosure(self, capsys):
        out = _run(capsys, ["plan"])
        assert "violations" in out
        assert "disclosure" in out


class TestArgumentsNotEdits:
    def test_a_second_profile_needs_no_file_change(self, capsys):
        out = _run(capsys, [
            "plan", "--weight-kg", "55", "--height-cm", "160",
            "--age-years", "30", "--sex", "female", "--activity", "light",
        ])
        assert "55kg / 160cm / 30 / female / light" in out

    def test_template_is_selectable(self, capsys):
        out = _run(capsys, ["plan", "--region", "south_indian",
                            "--meal-slot", "breakfast"])
        assert "south_indian / breakfast" in out
        assert "ENUMERATION -- south_breakfast" in out

    def test_clinical_flags_reach_the_profile(self, capsys):
        out = _run(capsys, ["plan", "--clinical-flag", "hypertension"])
        assert "clinical_flags=hypertension" in out

    def test_dev_mode_can_be_turned_off(self, capsys):
        # Not a claim about the verdict -- only that the flag is wired through
        # to the candidate filter and reported.
        out = _run(capsys, ["library", "--no-dev-mode"])
        assert "dev_mode=False" in out

    def test_an_unknown_choice_is_rejected_rather_than_defaulted(self, capsys):
        with pytest.raises(SystemExit):
            demo.main(["plan", "--sex", "not_a_sex"])

    def test_the_day_so_far_is_reported_even_when_it_is_empty(self, capsys):
        # A transcript must say which day-state produced its numbers. Silence
        # would read as "no ledger exists" rather than "the ledger was empty",
        # and those become different claims once sodium is budgeted.
        out = _run(capsys, ["plan"])
        assert "day so far" in out
        assert "nothing planned yet" in out

    def test_sodium_already_spent_reaches_the_ledger(self, capsys):
        out = _run(capsys, ["plan", "--sodium-spent-mg", "1200"])
        assert "1200.0mg spent" in out
        assert "nothing planned yet" not in out
